[general]
import = [
    "~/.config/alacritty/themes/themes/kanagawa_wave.toml"
]

[font]
size = 12.0
normal = { family = "JetBrainsMono Nerd Font" }

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F11"

[[keyboard.bindings]]
action = "CreateNewWindow"
key = "Enter"
mods = "Control"

[terminal.shell]
program = "fish"

[window]
decorations = "none"
# startup_mode = "Maximized"

[window.dimensions]
columns = 100
lines = 25

[terminal]
